services:
  # Jenkins
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_vete
    ports:
      - "8080:8080"
    networks:
      - vete-net
    volumes:
      - jenkins_home:/var/jenkins_home

  # SonarQube
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube_vete
    ports:
      - "9000:9000"
    networks:
      - vete-net

  # Base de Datos (usando tu Dockerfile)
  db:
    build: .
    container_name: mysql_vete
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: veterinaria
    ports:
      - "3307:3306"
    networks:
      - vete-net

# --- ESTA ES LA PARTE QUE TE FALTA ---
networks:
  vete-net:

volumes:
  jenkins_home: