spring.datasource.url=jdbc:mysql://localhost:3307/veterinaria
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
app.jwt.secret=926eb5ee9111c191a329583110292728